# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-02 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20180401_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
    ]
