# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-04 12:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_album_album_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.FileField(default=datetime.datetime(2018, 4, 4, 12, 59, 20, 229661, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
